image: Ubuntu  

stack: jdk 11 

branches:
  only:
    - main

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - chmod +x gradlew
  - java -jar ./artifacts/app-ibank.jar -P:profile=test.




build_script:
  #  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации
  - ./gradlew test -Dselenide.headless=true --info
